export type District = {
  name: string;
  slug: string;
  side: "Avrupa" | "Anadolu";
  neighborhoods: string[];
  character: string;
  sectors: string[];
  tier: 1 | 2 | 3;
};

export const districts: District[] = [
  {name:"Adalar",slug:"adalar",side:"Anadolu",tier:3,neighborhoods:["Büyükada","Heybeliada","Burgazada","Kınalıada"],character:"Motorlu taşıt kısıtlamasının olduğu, turizm ve yazlık nüfusa dayanan bir ada ilçesidir. İskele çevresindeki restoranlar, butik oteller ve bisiklet kiralama işletmeleri ekonominin temelini oluşturur.",sectors:["butik otel","restoran","kafe","turizm","bisiklet kiralama"]},
  {name:"Arnavutköy",slug:"arnavutkoy",side:"Avrupa",tier:3,neighborhoods:["Hadımköy","Taşoluk","Bolluca","Haraççı","Durusu"],character:"İstanbul Havalimanı'nın bulunduğu, hızla gelişen ancak hâlâ geniş kırsal alanlara sahip bir ilçedir. Hadımköy sanayi bölgesi, lojistik depolar ve havalimanına bağlı hizmet işletmeleri öne çıkar.",sectors:["lojistik","sanayi","depolama","havalimanı hizmetleri","tarım"]},
  {name:"Ataşehir",slug:"atasehir",side:"Anadolu",tier:1,neighborhoods:["Barbaros","Ataşehir Merkez","İçerenköy","Küçükbakkalköy","Yenisahra"],character:"İstanbul Finans Merkezi ve Barbaros Mahallesi'ndeki plazalarla Anadolu Yakası'nın kurumsal iş merkezidir. Palladium ve Watergarden gibi AVM'ler ile Ataşehir Bulvarı çevresindeki restoran ve kafeler yoğun bir hizmet ekonomisi oluşturur.",sectors:["finans","kurumsal ofis","plaza","AVM","restoran","teknoloji"]},
  {name:"Avcılar",slug:"avcilar",side:"Avrupa",tier:2,neighborhoods:["Ambarlı","Cihangir","Denizköşkler","Firuzköy","Yeşilkent"],character:"İstanbul Üniversitesi-Cerrahpaşa kampüsü ve E-5 üzerindeki ticaret aksıyla öğrenci nüfusu yüksek bir ilçedir. Ambarlı Limanı ilçeyi lojistik ve ithalat-ihracat faaliyetlerinin merkezi yapar.",sectors:["lojistik","liman","öğrenci kafeleri","perakende","otomotiv"]},
  {name:"Bağcılar",slug:"bagcilar",side:"Avrupa",tier:2,neighborhoods:["Güneşli","Mahmutbey","Bağcılar Merkez","Kirazlı","Yenibosna sınırı"],character:"İstanbul'un en kalabalık ilçelerinden biri olup Güneşli ve Mahmutbey'de tekstil, matbaa ve medya kuruluşları yoğunlaşır. Küçük ölçekli imalat atölyeleri ve toptan ticaret ilçe ekonomisinin omurgasıdır.",sectors:["tekstil","matbaa","medya","toptan ticaret","imalat"]},
  {name:"Bahçelievler",slug:"bahcelievler",side:"Avrupa",tier:1,neighborhoods:["Yenibosna","Şirinevler","Bahçelievler Merkez","Kocasinan","Soğanlı"],character:"Yenibosna'daki plazalar, Şirinevler'in yoğun perakende ve gıda sektörü ile E-5 aksındaki hastanelerle karma bir ticaret ilçesidir. Metrobüs hattı çevresinde küçük işletme yoğunluğu çok yüksektir.",sectors:["perakende","sağlık","plaza","restoran","eğitim"]},
  {name:"Bakırköy",slug:"bakirkoy",side:"Avrupa",tier:1,neighborhoods:["Ataköy","Yeşilköy","Florya","Bakırköy Çarşı","Yeşilyurt"],character:"Bakırköy Çarşı ve Capacity, Galleria gibi AVM'lerle Avrupa Yakası'nın köklü ticaret merkezlerindendir. Yeşilköy ve Florya sahil hattı restoranları, özel hastaneler ve Ataköy Marina bölgesi güçlü bir hizmet ekonomisi oluşturur.",sectors:["perakende","AVM","sağlık","restoran","marina","eğitim"]},
  {name:"Başakşehir",slug:"basaksehir",side:"Avrupa",tier:1,neighborhoods:["Bahçeşehir","Kayaşehir","İkitelli","Başak","Ziya Gökalp"],character:"İkitelli Organize Sanayi Bölgesi ile Bahçeşehir ve Kayaşehir'in planlı konut alanlarını barındıran yeni nesil bir ilçedir. Mall of İstanbul, Başakşehir Şehir Hastanesi ve OSB'deki binlerce KOBİ ilçeyi hem sanayi hem tüketim merkezi yapar.",sectors:["OSB sanayi","KOBİ","AVM","sağlık","konut projeleri","kafe"]},
  {name:"Bayrampaşa",slug:"bayrampasa",side:"Avrupa",tier:2,neighborhoods:["Terazidere","Yenidoğan","Kartaltepe","Altıntepsi","İsmetpaşa"],character:"Forum İstanbul AVM, otogarın yakınlığı ve tekstil-deri atölyeleriyle üretim ağırlıklı bir ilçedir. Terazidere ve Yenidoğan'da toptan ve küçük sanayi işletmeleri yoğundur.",sectors:["tekstil","toptan ticaret","AVM","imalat","lojistik"]},
  {name:"Beşiktaş",slug:"besiktas",side:"Avrupa",tier:1,neighborhoods:["Levent","Etiler","Bebek","Akaretler","Ortaköy","Arnavutköy"],character:"Levent'teki gökdelenler ve holding merkezleriyle Türkiye'nin kurumsal kalbidir. Bebek, Ortaköy ve Arnavutköy'ün Boğaz kıyısındaki restoran-kafe kültürü ile Etiler ve Akaretler'in lüks perakendesi premium bir pazar oluşturur.",sectors:["kurumsal holding","finans","lüks restoran","kafe","gece hayatı","lüks perakende","üniversite"]},
  {name:"Beykoz",slug:"beykoz",side:"Anadolu",tier:2,neighborhoods:["Kavacık","Çubuklu","Anadolu Hisarı","Paşabahçe","Riva","Polonezköy"],character:"Boğaz'ın Anadolu kıyısında yeşil alanları, köyleri ve sahil restoranlarıyla bilinen bir ilçedir. Kavacık plazaları ve Riva-Polonezköy'deki kır düğünü mekanları, butik oteller ve sahil kahvaltı restoranları öne çıkar.",sectors:["sahil restoran","düğün mekanı","butik otel","plaza","turizm","köy işletmeleri"]},
  {name:"Beylikdüzü",slug:"beylikduzu",side:"Avrupa",tier:1,neighborhoods:["Yakuplu","Beylikdüzü Merkez","Gürpınar","Kavaklı","Büyükşehir"],character:"Planlı siteleri, Marmara Park ve Torium AVM'leri ile Avrupa Yakası'nın batısındaki genç ve hızlı büyüyen bir ilçedir. Beylikdüzü OSB, Tüyap Fuar Merkezi ve Gürpınar sahilindeki restoranlar ekonomik çeşitliliği sağlar.",sectors:["AVM","fuar","OSB sanayi","restoran","emlak","eğitim"]},
  {name:"Beyoğlu",slug:"beyoglu",side:"Avrupa",tier:1,neighborhoods:["Taksim","Galata","Karaköy","Cihangir","Kasımpaşa","Tophane"],character:"İstiklal Caddesi, Galata ve Karaköy ile İstanbul'un kültür, turizm ve eğlence merkezidir. Butik oteller, kafeler, bar-restoranlar, galeriler ve Karaköy'deki tasarım stüdyoları turist odaklı yoğun bir hizmet ekonomisi oluşturur.",sectors:["turizm","otel","kafe","restoran","gece hayatı","sanat galerisi","tasarım stüdyosu"]},
  {name:"Büyükçekmece",slug:"buyukcekmece",side:"Avrupa",tier:2,neighborhoods:["Mimarsinan","Kumburgaz","Tepecik","Kavaklı","Alkent"],character:"Büyükçekmece Gölü ve Marmara sahili boyunca yazlık, düğün salonu ve sahil restoranlarıyla bilinen bir ilçedir. Kumburgaz'ın yazlık nüfusu ve Alkent gibi lüks siteler mevsimsel bir hizmet talebi oluşturur.",sectors:["düğün salonu","sahil restoran","yazlık turizm","emlak","gıda"]},
  {name:"Çatalca",slug:"catalca",side:"Avrupa",tier:3,neighborhoods:["Çatalca Merkez","Kestanelik","Binkılıç","Karacaköy","İhsaniye"],character:"İstanbul'un en geniş yüzölçümlü ve en az nüfuslu ilçelerinden biri olup tarım, hayvancılık ve kırsal turizme dayanır. Çiftlikler, kır düğünü mekanları ve köy kahvaltı işletmeleri başlıca ticari faaliyetlerdir.",sectors:["tarım","hayvancılık","kır düğünü","köy kahvaltısı","çiftlik"]},
  {name:"Çekmeköy",slug:"cekmekoy",side:"Anadolu",tier:2,neighborhoods:["Alemdağ","Taşdelen","Ömerli","Mehmet Akif","Soğukpınar"],character:"Ormanlık alanlar ve yeni konut siteleriyle Anadolu Yakası'nın gelişen bir ilçesidir. Alemdağ ve Taşdelen'de küçük sanayi, mobilya ve inşaat malzemeleri işletmeleri ile Ömerli'de kır düğünü mekanları bulunur.",sectors:["mobilya","küçük sanayi","emlak","düğün mekanı","market"]},
  {name:"Esenler",slug:"esenler",side:"Avrupa",tier:3,neighborhoods:["Oruçreis","Davutpaşa","Menderes","Fevzi Çakmak","Havaalanı"],character:"Yıldız Teknik Üniversitesi Davutpaşa kampüsü ve Tekstilkent ile tekstil sektörünün merkezlerinden biridir. Esenler Otogarı ilçeyi ulaşım ve küçük esnaf açısından hareketli kılar.",sectors:["tekstil","toptan ticaret","üniversite","esnaf","ulaşım"]},
  {name:"Esenyurt",slug:"esenyurt",side:"Avrupa",tier:2,neighborhoods:["Esenyurt Merkez","Kıraç","Mehterçeşme","Saadetdere","Akçaburgaz"],character:"Türkiye'nin en kalabalık ilçesi olup yüksek katlı siteler ve yoğun bir esnaf dokusuna sahiptir. Kıraç ve Akçaburgaz'daki sanayi siteleri, çok sayıda restoran, mobilya ve beyaz eşya mağazası ile büyük bir tüketici pazarı oluşturur.",sectors:["perakende","sanayi","restoran","mobilya","emlak","eğitim"]},
  {name:"Eyüpsultan",slug:"eyupsultan",side:"Avrupa",tier:2,neighborhoods:["Eyüp Merkez","Alibeyköy","Göktürk","Kemerburgaz","Rami"],character:"Eyüp Sultan Camii çevresinde dini turizm ile Göktürk ve Kemerburgaz'ın lüks sitelerini bir arada barındıran karma bir ilçedir. İsfanbul, Alibeyköy'deki lojistik ve Göktürk'ün kafe-restoranları farklı pazarlar sunar.",sectors:["dini turizm","kafe","restoran","emlak","lojistik","tema parkı"]},
  {name:"Fatih",slug:"fatih",side:"Avrupa",tier:1,neighborhoods:["Sultanahmet","Eminönü","Laleli","Aksaray","Fener-Balat","Kapalıçarşı"],character:"Tarihi Yarımada olarak Sultanahmet, Kapalıçarşı ve Eminönü ile İstanbul'un turizm ve geleneksel ticaret merkezidir. Laleli'nin toptan tekstil ihracatı, Sultanahmet otelleri ve Balat'ın kafeleri çok katmanlı bir ekonomi oluşturur.",sectors:["turizm","otel","toptan tekstil","restoran","kafe","hediyelik eşya","sağlık turizmi"]},
  {name:"Gaziosmanpaşa",slug:"gaziosmanpasa",side:"Avrupa",tier:3,neighborhoods:["Küçükköy","Karadeniz","Yıldıztabya","Barbaros Hayrettin Paşa","Sarıgöl"],character:"Yoğun nüfuslu, kentsel dönüşümün hızlandığı bir ilçedir. Küçükköy ve Karadeniz Mahallesi'ndeki esnaf çarşıları, küçük imalat ve gıda toptancıları ekonominin ana unsurlarıdır.",sectors:["esnaf","perakende","küçük imalat","gıda","inşaat"]},
  {name:"Güngören",slug:"gungoren",side:"Avrupa",tier:2,neighborhoods:["Merter","Tozkoparan","Güneştepe","Gençosman","Haznedar"],character:"Merter, Türkiye'nin en büyük hazır giyim toptan merkezlerinden biridir ve ilçe ekonomisine yön verir. Küçük yüzölçümüne rağmen tekstil showroom'ları, konfeksiyon atölyeleri ve toptan ticaret yoğunluğu çok yüksektir.",sectors:["hazır giyim toptan","tekstil showroom","konfeksiyon","perakende"]},
  {name:"Kadıköy",slug:"kadikoy",side:"Anadolu",tier:1,neighborhoods:["Moda","Bahariye","Bağdat Caddesi","Fenerbahçe","Yeldeğirmeni","Kozyatağı","Fikirtepe"],character:"Moda ve Bahariye'nin kafe-bar kültürü ile Bağdat Caddesi'nin marka mağazaları ve restoranlarıyla Anadolu Yakası'nın kültür ve perakende başkentidir. Kozyatağı plazaları, Yeldeğirmeni'nin genç girişimleri ve Fikirtepe'nin yeni konut projeleri farklı hedef kitleler sunar.",sectors:["kafe","restoran","bar","perakende","butik","plaza","sanat","spor kulübü"]},
  {name:"Kağıthane",slug:"kagithane",side:"Avrupa",tier:2,neighborhoods:["Çağlayan","Gültepe","Seyrantepe","Hamidiye","Nurtepe"],character:"Levent ve Maslak'a komşuluğuyla plaza ve ofis projelerinin hızla arttığı, kentsel dönüşüm yoğun bir ilçedir. Çağlayan Adliyesi çevresindeki hukuk büroları, Seyrantepe'deki teknoloji firmaları ve Vadistanbul ilçeyi yeni bir iş merkezi haline getirmiştir.",sectors:["ofis","plaza","hukuk","teknoloji","AVM","medya"]},
  {name:"Kartal",slug:"kartal",side:"Anadolu",tier:1,neighborhoods:["Kartal Merkez","Soğanlık","Yakacık","Uğurmumcu","Orhantepe"],character:"Anadolu Adliyesi ve sahil boyunca yükselen ofis kuleleriyle Anadolu Yakası'nın yeni iş merkezlerinden biridir. Kartal sahili restoranları, hukuk büroları, özel hastaneler ve Yakacık'taki sanayi siteleri ekonomiyi çeşitlendirir.",sectors:["hukuk","ofis","sağlık","sahil restoran","sanayi","emlak"]},
  {name:"Küçükçekmece",slug:"kucukcekmece",side:"Avrupa",tier:2,neighborhoods:["Halkalı","Sefaköy","Atakent","Cennet","İkitelli sınırı"],character:"Küçükçekmece Gölü çevresinde Halkalı, Sefaköy ve Atakent gibi büyük konut ve ticaret alanlarını barındıran kalabalık bir ilçedir. Sefaköy'ün esnaf yoğunluğu, ArenaPark ve 212 AVM ile Halkalı'daki toplu konut projeleri geniş bir tüketici pazarı sunar.",sectors:["perakende","AVM","esnaf","emlak","eğitim","sağlık"]},
  {name:"Maltepe",slug:"maltepe",side:"Anadolu",tier:1,neighborhoods:["Cevizli","Altıntepe","Küçükyalı","İdealtepe","Maltepe Merkez"],character:"Maltepe Sahil Parkı, Piazza AVM ve Bağdat Caddesi'nin doğu uzantısıyla sahil odaklı bir yaşam ve ticaret alanıdır. Cevizli ve Küçükyalı'daki eğitim kurumları, özel hastaneler ve sahil restoranları ilçe ekonomisini şekillendirir.",sectors:["sahil restoran","kafe","AVM","eğitim","sağlık","emlak"]},
  {name:"Pendik",slug:"pendik",side:"Anadolu",tier:1,neighborhoods:["Kurtköy","Kaynarca","Pendik Merkez","Şeyhli","Yenişehir"],character:"Sabiha Gökçen Havalimanı, Teknopark İstanbul ve Kurtköy'ün lojistik-ofis alanlarıyla Anadolu Yakası'nın sanayi ve teknoloji odağıdır. Pendik Marina ve sahil restoranları, Viaport Asia AVM ile hizmet sektörü de güçlüdür.",sectors:["teknoloji","havalimanı","lojistik","sanayi","marina","AVM","restoran"]},
  {name:"Sancaktepe",slug:"sancaktepe",side:"Anadolu",tier:2,neighborhoods:["Sarıgazi","Samandıra","Yenidoğan","Emek","Abdurrahmangazi"],character:"Sarıgazi ve Samandıra çevresinde hızla büyüyen, genç nüfuslu bir konut ilçesidir. Küçük sanayi siteleri, mobilya ve inşaat malzemesi satıcıları ile yerel esnaf ekonominin temelini oluşturur.",sectors:["esnaf","küçük sanayi","mobilya","market","emlak"]},
  {name:"Sarıyer",slug:"sariyer",side:"Avrupa",tier:1,neighborhoods:["Maslak","İstinye","Tarabya","Zekeriyaköy","Rumelihisarı","Kilyos"],character:"Maslak'ın gökdelenleri ve teknoloji şirketleri ile Boğaz kıyısındaki İstinye, Tarabya ve Yeniköy'ün balık restoranlarını birleştiren prestijli bir ilçedir. Zekeriyaköy'ün villa siteleri, İstinyePark, Koç ve Boğaziçi üniversiteleri ile Kilyos plajları çeşitli premium pazarlar sunar.",sectors:["kurumsal ofis","teknoloji","lüks restoran","balık restoranı","AVM","üniversite","villa emlak","plaj"]},
  {name:"Silivri",slug:"silivri",side:"Avrupa",tier:3,neighborhoods:["Silivri Merkez","Selimpaşa","Gümüşyaka","Kavaklı","Değirmenköy"],character:"İstanbul'un batı ucunda yazlık siteler, sahil ve tarım alanlarıyla mevsimsel bir ekonomiye sahiptir. Yoğurdu, sahil restoranları, yazlık emlak piyasası ve Selimpaşa'daki tesisler ana ticari faaliyetlerdir.",sectors:["yazlık turizm","sahil restoran","tarım","emlak","gıda üretimi"]},
  {name:"Sultanbeyli",slug:"sultanbeyli",side:"Anadolu",tier:3,neighborhoods:["Abdurrahmangazi","Fatih","Mecidiye","Battalgazi","Hamidiye"],character:"Anadolu Yakası'nın yoğun nüfuslu ve esnaf odaklı ilçelerindendir. Fatih Bulvarı üzerindeki mağazalar, mobilya ve gıda esnafı ile küçük atölyeler yerel ekonomiyi oluşturur.",sectors:["esnaf","perakende","mobilya","gıda","inşaat"]},
  {name:"Sultangazi",slug:"sultangazi",side:"Avrupa",tier:3,neighborhoods:["Sultançiftliği","Cebeci","Habibler","Gazi","Uğur Mumcu"],character:"Kalabalık, genç nüfuslu ve esnaf ağırlıklı bir ilçedir. Cebeci'deki taş ocakları ve sanayi siteleri ile Sultançiftliği'nin mahalle çarşıları ekonomik faaliyetin merkezidir.",sectors:["esnaf","sanayi sitesi","inşaat malzemesi","gıda","perakende"]},
  {name:"Şile",slug:"sile",side:"Anadolu",tier:3,neighborhoods:["Şile Merkez","Ağva","Kumbaba","Sahilköy","Yeşilvadi"],character:"Karadeniz kıyısında plajları, Ağva'daki nehir otelleri ve Şile bezi ile bilinen bir turizm ilçesidir. Butik oteller, pansiyonlar, balık restoranları ve düğün-organizasyon mekanları yaz sezonunda yoğun talep görür.",sectors:["butik otel","pansiyon","plaj","balık restoranı","düğün mekanı","Şile bezi"]},
  {name:"Şişli",slug:"sisli",side:"Avrupa",tier:1,neighborhoods:["Nişantaşı","Mecidiyeköy","Osmanbey","Teşvikiye","Bomonti","Fulya"],character:"Nişantaşı ve Teşvikiye'nin lüks butikleri, Mecidiyeköy'ün plazaları ve Osmanbey'in tekstil toptancılarıyla İstanbul'un en yoğun ticaret ilçelerindendir. Bomonti'nin yeni kafe-bar sahnesi, Cevahir AVM ve çok sayıda özel hastane ilçeyi çok yönlü bir pazar yapar.",sectors:["lüks perakende","butik","plaza","tekstil toptan","kafe","restoran","sağlık","AVM"]},
  {name:"Tuzla",slug:"tuzla",side:"Anadolu",tier:2,neighborhoods:["Aydınlı","İçmeler","Orhanlı","Tersane bölgesi","Mimar Sinan"],character:"Tersaneler, Tuzla Organize Sanayi Bölgeleri ve Deri OSB ile İstanbul'un ağır sanayi merkezidir. Sabancı Üniversitesi, Marina ve sahil restoranları sanayi dışında da bir hizmet talebi oluşturur.",sectors:["tersane","OSB sanayi","deri","otomotiv yan sanayi","lojistik","üniversite","marina"]},
  {name:"Ümraniye",slug:"umraniye",side:"Anadolu",tier:1,neighborhoods:["Çakmak","Dudullu","Atakent","İnkılap","Şerifali"],character:"Dudullu OSB ve Şerifali'deki plazalar ile Anadolu Yakası'nın en büyük sanayi ve ofis yoğunluklarından birine sahiptir. Meydan, Buyaka ve Canpark AVM'leri ile Alemdağ Caddesi'nin esnafı güçlü bir tüketici pazarı sunar.",sectors:["OSB sanayi","plaza","AVM","perakende","mobilya","teknoloji","restoran"]},
  {name:"Üsküdar",slug:"uskudar",side:"Anadolu",tier:1,neighborhoods:["Kuzguncuk","Çengelköy","Beylerbeyi","Altunizade","Kısıklı","Bağlarbaşı"],character:"Boğaz kıyısında Kuzguncuk, Çengelköy ve Beylerbeyi'nin tarihi dokusu ve kahvaltı-restoran kültürü ile Altunizade'nin plazalarını birleştirir. Çamlıca Kulesi, üniversite hastaneleri ve Kısıklı'nın müstakil konutları farklı hizmet talepleri yaratır.",sectors:["kahvaltı restoran","kafe","plaza","sağlık","eğitim","tarihi turizm"]},
  {name:"Zeytinburnu",slug:"zeytinburnu",side:"Avrupa",tier:2,neighborhoods:["Merkezefendi","Kazlıçeşme","Topkapı","Telsiz","Sümer"],character:"Deri ve tekstil sanayisiyle tanınan, Kazlıçeşme sahilinde büyük dönüşüm projelerinin yükseldiği bir ilçedir. Olivium AVM, sağlık turizmi hastaneleri ve Topkapı'daki toptan ticaret ilçe ekonomisini şekillendirir.",sectors:["tekstil","deri","sağlık turizmi","AVM","toptan ticaret","emlak"]},
];

export const getDistrict = (slug: string) => districts.find((d) => d.slug === slug);
