/**
 * Türkiye geneli cam tablo il sayfaları (/cam-tablo/[il]).
 * Plaka, bölge ve kargo süresi tobecreative.net il sayfalarıyla aynıdır; notlar bu siteye özgüdür.
 * İstanbul burada yok: İstanbul'un karşılığı /cam-tablo hub'ı ve ilçe sayfalarıdır.
 */
export type Il = {
  plaka: number;
  slug: string;
  name: string;
  bolge: Bolge;
  /** Kargoya verildikten sonra teslim süresi (iş günü) */
  kargo: string;
  /** Teslimat bölümünde anılan başlıca ilçeler */
  ilceler: string[];
  /** İle özgü konut ve dekorasyon notu */
  note: string;
};

export type Bolge = "Marmara" | "Ege" | "Akdeniz" | "İç Anadolu" | "Karadeniz" | "Doğu Anadolu" | "Güneydoğu Anadolu";

export const bolgeler: Bolge[] = ["Marmara", "Ege", "Akdeniz", "İç Anadolu", "Karadeniz", "Doğu Anadolu", "Güneydoğu Anadolu"];

export const iller: Il[] = [
  { plaka: 1, slug: "adana", name: "Adana", bolge: "Akdeniz", kargo: "2–4", ilceler: ["Seyhan", "Çukurova", "Yüreğir", "Sarıçam", "Ceyhan", "Kozan"], note: "Adana'nın Çukurova ve Seyhan'daki geniş, yüksek tavanlı sitelerinde salon duvarları büyük ölçüye elverişlidir; 80×125 ve 90×140 cm soyut altın ve otomobil tasarımları sıcak, canlı mekânlarla iyi eşleşir. Nemli ve sıcak yaz aylarında cam yüzeyin bozulmaması da kanvasa göre avantajdır." },
  { plaka: 2, slug: "adiyaman", name: "Adıyaman", bolge: "Güneydoğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Kahta", "Besni", "Gölbaşı"], note: "Adıyaman'da yenilenen konutlarda aile salonları için sade, açık tonlu soyut tablolar ve Nemrut'un taş dokusunu hatırlatan toprak renkli tasarımlar öne çıkar; genç odalarında spor ve anime temaları sık tercih edilir." },
  { plaka: 3, slug: "afyonkarahisar", name: "Afyonkarahisar", bolge: "Ege", kargo: "2–3", ilceler: ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "Emirdağ"], note: "Afyonkarahisar'daki termal oteller ve butik konaklama tesislerinde lobiler için panoramik manzara ve mermer dokulu soyut cam tablolar talep görür; mermeriyle bilinen şehrin evlerinde de altın-mermer tonlu tasarımlar mekâna uyum sağlar." },
  { plaka: 4, slug: "agri", name: "Ağrı", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Doğubayazıt", "Patnos", "Diyadin"], note: "Ağrı'nın uzun ve soğuk kışlarında evin içi daha çok yaşanır; salonlarda sıcak tonlu soyut tablolar ve Ağrı Dağı'nı çağrıştıran panoramik manzaralar duvara derinlik katar. Doğubayazıt'taki otel ve pansiyonlarda da manzara temalı büyük ölçüler tercih edilir." },
  { plaka: 5, slug: "amasya", name: "Amasya", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Merzifon", "Suluova", "Taşova"], note: "Amasya'nın Yeşilırmak kıyısındaki tarihi evlerinde ve butik otellerinde klasik eser yorumları ve natürmort tasarımlar mekânın karakteriyle uyuşur; yeni sitelerde ise minimal soyut ve doğa temaları öne çıkar." },
  { plaka: 6, slug: "ankara", name: "Ankara", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Çankaya", "Yenimahalle", "Keçiören", "Etimesgut", "Gölbaşı", "Sincan", "Mamak", "Pursaklar"], note: "Ankara'da Çankaya ve Gölbaşı'nın geniş dairelerinde minimal ve soyut altın tasarımlar, Etimesgut ve Yenimahalle'nin yeni sitelerinde 3'lü koltuk üstü düzenler öne çıkar. Kamu kurumları, hukuk büroları ve kliniklerin yoğun olduğu şehirde ofis ve bekleme salonları için sade, kurumsal görünümlü cam tablolar da sık tercih edilir." },
  { plaka: 7, slug: "antalya", name: "Antalya", bolge: "Akdeniz", kargo: "2–4", ilceler: ["Muratpaşa", "Konyaaltı", "Kepez", "Alanya", "Manavgat", "Kemer", "Kaş"], note: "Antalya'nın villa, apart ve otel projelerinde deniz ve gün batımı temalı panoramik tasarımlar ile sıcak tonlu soyut kompozisyonlar öne çıkar. Nem ve güneşten etkilenmeyen, silinerek temizlenen cam yüzey; kafe, restoran ve kliniklerde de hijyen avantajı sağlar." },
  { plaka: 8, slug: "artvin", name: "Artvin", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Hopa", "Arhavi", "Borçka", "Yusufeli"], note: "Artvin'in yeşil vadilere bakan evlerinde ve Hopa-Arhavi sahilindeki dairelerde doğa, orman ve kuş temalı tasarımlar dışarıdaki manzarayı içeri taşır; Karadeniz nemine dayanıklı cam yüzey burada ayrıca avantajlıdır." },
  { plaka: 9, slug: "aydin", name: "Aydın", bolge: "Ege", kargo: "2–3", ilceler: ["Efeler", "Kuşadası", "Didim", "Nazilli", "Söke"], note: "Aydın'da Kuşadası ve Didim'in yazlık evleriyle pansiyonlarında deniz temalı ve açık tonlu tasarımlar, Efeler ve Nazilli'deki aile evlerinde ise klasik eser yorumları ve sevimli hayvan temaları sık tercih edilir." },
  { plaka: 10, slug: "balikesir", name: "Balıkesir", bolge: "Marmara", kargo: "1–3", ilceler: ["Karesi", "Altıeylül", "Bandırma", "Edremit", "Ayvalık", "Burhaniye"], note: "Balıkesir'de Ayvalık, Edremit ve Burhaniye'deki taş evler ve yazlıklar için zeytin, deniz ve Ege ışığıyla uyumlu açık tonlu tasarımlar; Bandırma ve merkezdeki modern dairelerde ise soyut ve otomobil temalı büyük ölçüler öne çıkar." },
  { plaka: 11, slug: "bilecik", name: "Bilecik", bolge: "Marmara", kargo: "1–3", ilceler: ["Merkez", "Bozüyük", "Osmaneli", "Söğüt"], note: "Bilecik'in Bozüyük sanayi bölgesindeki ofis ve fabrika idari binalarında kurumsal cam tablolar, merkezdeki aile evlerinde ise klasik eserler ve doğa temalı orta ölçüler (60×90) tercih edilir." },
  { plaka: 12, slug: "bingol", name: "Bingöl", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Genç", "Solhan", "Karlıova"], note: "Bingöl'ün yeni konut alanlarında aile salonları için göz yormayan soyut ve doğa temaları, üniversite öğrencilerinin yoğun olduğu kira evlerinde ise 35×50 ve 50×70 ölçüde spor ve anime tasarımları öne çıkar." },
  { plaka: 13, slug: "bitlis", name: "Bitlis", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Tatvan", "Ahlat", "Adilcevaz"], note: "Bitlis'te Tatvan ve Ahlat'ın Van Gölü'ne bakan evlerinde göl ve dağ manzaralı panoramik tasarımlar, taş dokulu tarihi yapılarda ise klasik eser yorumları mekânla uyum sağlar." },
  { plaka: 14, slug: "bolu", name: "Bolu", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Gerede", "Mudurnu", "Mengen"], note: "Bolu'nun Abant ve Gölcük çevresindeki bungalov, dağ evi ve otellerinde orman, kurt-ayı ve göl temalı tasarımlar mekânın doğasıyla bütünleşir; merkezdeki öğrenci evlerinde ise küçük ölçülü poster setleri öne çıkar." },
  { plaka: 15, slug: "burdur", name: "Burdur", bolge: "Akdeniz", kargo: "2–4", ilceler: ["Merkez", "Bucak", "Gölhisar", "Yeşilova"], note: "Burdur'un sakin aile evlerinde göl ve doğa temalı panoramikler, Salda Gölü'nün turkuaz tonlarını yansıtan açık renkli soyut tasarımlar ve mutfak için 35×50 ölçüde renkli tablolar tercih edilir." },
  { plaka: 16, slug: "bursa", name: "Bursa", bolge: "Marmara", kargo: "1–3", ilceler: ["Nilüfer", "Osmangazi", "Yıldırım", "Mudanya", "İnegöl", "Gemlik"], note: "Bursa'da Nilüfer ve Mudanya'nın modern sitelerinde büyük ölçülü soyut ve otomobil tasarımları öne çıkar; otomotiv yan sanayisinin güçlü olduğu şehirde klasik otomobil ve Formula 1 koleksiyonları ofislerde de ilgi görür. İnegöl'ün mobilya showroom'larında teşhir amaçlı cam tablolar sık kullanılır." },
  { plaka: 17, slug: "canakkale", name: "Çanakkale", bolge: "Marmara", kargo: "1–3", ilceler: ["Merkez", "Biga", "Gelibolu", "Ayvacık", "Çan", "Bozcaada"], note: "Çanakkale'nin Bozcaada, Assos ve Gelibolu'daki butik otel ve taş evlerinde deniz ve panoramik manzara tasarımları, üniversite şehri kimliğiyle öğrenci evlerinde ise sinema, müzik ve estetik poster temaları öne çıkar." },
  { plaka: 18, slug: "cankiri", name: "Çankırı", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Merkez", "Ilgaz", "Çerkeş", "Şabanözü"], note: "Çankırı'nın aile evlerinde klasik eser ve doğa temalı tablolar, Ilgaz Dağı çevresindeki dağ evleri ve konaklama tesislerinde orman ve kar manzaralı panoramik tasarımlar tercih edilir." },
  { plaka: 19, slug: "corum", name: "Çorum", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Sungurlu", "Osmancık", "İskilip"], note: "Çorum'un yeni sitelerindeki geniş salonlarda 3'lü koltuk üstü soyut ve altın detaylı tasarımlar, Hitit mirasının şehri olarak klasik ve tarihi doku taşıyan tablolar da ilgi görür; işyerlerinde kurumsal cam tablolar yaygındır." },
  { plaka: 20, slug: "denizli", name: "Denizli", bolge: "Ege", kargo: "2–3", ilceler: ["Pamukkale", "Merkezefendi", "Çivril", "Sarayköy", "Buldan"], note: "Denizli'de tekstil firmalarının ofis ve showroom'larında marka görselli ve modern soyut cam tablolar, Pamukkale ve Merkezefendi'nin yeni dairelerinde ise beyaz ve açık tonlarla uyumlu minimal tasarımlar öne çıkar." },
  { plaka: 21, slug: "diyarbakir", name: "Diyarbakır", bolge: "Güneydoğu Anadolu", kargo: "3–5", ilceler: ["Kayapınar", "Bağlar", "Yenişehir", "Sur", "Ergani"], note: "Diyarbakır'ın Kayapınar'daki geniş ve yeni sitelerinde büyük ölçülü soyut altın ve lüks temalı tasarımlar, Sur'daki taş konak, kafe ve butik otellerde ise klasik eser yorumları ve sıcak tonlu tablolar mekânın dokusunu tamamlar." },
  { plaka: 22, slug: "edirne", name: "Edirne", bolge: "Marmara", kargo: "1–3", ilceler: ["Merkez", "Keşan", "Uzunköprü", "İpsala", "Enez"], note: "Edirne'nin tarihi merkezindeki kafe ve otellerde klasik eser ve şehir-mimari temalı tasarımlar, öğrenci yoğunluğu nedeniyle kira evlerinde ise 50×70 ölçüde spor, müzik ve sinema temaları öne çıkar." },
  { plaka: 23, slug: "elazig", name: "Elazığ", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Kovancılar", "Karakoçan", "Palu"], note: "Elazığ'da deprem sonrası yenilenen konutlarda sade, ferah ve açık tonlu soyut tablolar, Hazar Gölü çevresindeki yazlık ve tesislerde ise göl ve doğa temalı panoramikler tercih edilir." },
  { plaka: 24, slug: "erzincan", name: "Erzincan", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Üzümlü", "Tercan", "Refahiye"], note: "Erzincan'ın yeni konut bölgelerindeki aile evlerinde doğa, at ve vahşi yaşam temalı tasarımlar; Ergan Dağı kayak merkezi çevresindeki konaklama tesislerinde ise kar ve dağ manzaralı büyük ölçüler öne çıkar." },
  { plaka: 25, slug: "erzurum", name: "Erzurum", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Yakutiye", "Palandöken", "Aziziye", "Oltu", "Horasan"], note: "Erzurum'un Palandöken otelleri ve kayak evlerinde dağ, kar ve kurt-ayı temalı tasarımlar; Yakutiye ve Palandöken'deki aile dairelerinde uzun kışa karşı sıcak tonlu soyut tablolar, öğrenci evlerinde ise anime ve spor temaları sık tercih edilir." },
  { plaka: 26, slug: "eskisehir", name: "Eskişehir", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Tepebaşı", "Odunpazarı", "Sivrihisar", "Alpu"], note: "Eskişehir'in öğrenci ve genç nüfusu nedeniyle Tepebaşı ve Odunpazarı'ndaki evlerde pop art, anime, müzik ve estetik poster temaları öne çıkar; Odunpazarı'nın renkli tarihi evlerinde ve kafelerinde ise sanatsal, canlı renkli tasarımlar karakter katar." },
  { plaka: 27, slug: "gaziantep", name: "Gaziantep", bolge: "Güneydoğu Anadolu", kargo: "3–5", ilceler: ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye"], note: "Gaziantep'in Şehitkamil'deki geniş dairelerinde lüks, altın detaylı soyut ve büyük ölçülü tasarımlar öne çıkar; sanayi ve ihracat firmalarının ofislerinde kurumsal cam tablolar, restoranlarda ise silinebilir yüzey avantajıyla büyük panoramikler tercih edilir." },
  { plaka: 28, slug: "giresun", name: "Giresun", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Bulancak", "Espiye", "Görele", "Tirebolu"], note: "Giresun'un sahil dairelerinde deniz ve doğa temalı tasarımlar, yayla evlerinde ise orman ve kuş temaları mekânla bütünleşir; Karadeniz'in nemli ikliminde cam yüzeyin küflenmemesi ve silinebilmesi önemli bir avantajdır." },
  { plaka: 29, slug: "gumushane", name: "Gümüşhane", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Kelkit", "Şiran", "Torul"], note: "Gümüşhane'nin aile evlerinde doğa ve dağ manzaralı panoramikler, üniversite öğrencilerinin kira evlerinde ise küçük ölçülü motivasyon yazılı ve spor temalı tablolar öne çıkar." },
  { plaka: 30, slug: "hakkari", name: "Hakkari", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Yüksekova", "Şemdinli", "Çukurca"], note: "Hakkari'nin dağlarla çevrili evlerinde salon için sıcak tonlu soyut tablolar ve vahşi doğa temaları, Yüksekova'daki yeni konutlarda ise 3'lü koltuk üstü düzenler tercih edilir; teslimat kargoyla adrese yapılır." },
  { plaka: 31, slug: "hatay", name: "Hatay", bolge: "Akdeniz", kargo: "2–4", ilceler: ["Antakya", "İskenderun", "Defne", "Dörtyol", "Samandağ"], note: "Hatay'da yeniden inşa edilen konut ve işyerlerinde ferah, açık tonlu ve umut veren tasarımlar öne çıkar; İskenderun'un sahil dairelerinde deniz temalı panoramikler, Antakya'nın restoran ve kafelerinde ise silinebilir cam yüzeyli büyük tablolar tercih edilir." },
  { plaka: 32, slug: "isparta", name: "Isparta", bolge: "Akdeniz", kargo: "2–4", ilceler: ["Merkez", "Eğirdir", "Yalvaç", "Şarkikaraağaç"], note: "Isparta'da gül bahçeleriyle özdeşleşen şehrin evlerinde çiçek ve natürmort içeren klasik eser tasarımları, Eğirdir Gölü çevresindeki pansiyonlarda göl manzaralı panoramikler, öğrenci evlerinde ise genç temalar öne çıkar." },
  { plaka: 33, slug: "mersin", name: "Mersin", bolge: "Akdeniz", kargo: "2–4", ilceler: ["Yenişehir", "Mezitli", "Toroslar", "Akdeniz", "Tarsus", "Erdemli", "Silifke"], note: "Mersin'in Mezitli ve Yenişehir'deki deniz manzaralı yüksek katlı sitelerinde büyük ölçülü minimal ve deniz temalı tasarımlar, liman ve lojistik firmalarının ofislerinde ise kurumsal cam tablolar öne çıkar; sıcak ve nemli iklimde cam yüzey kanvastan daha dayanıklıdır." },
  { plaka: 35, slug: "izmir", name: "İzmir", bolge: "Ege", kargo: "2–3", ilceler: ["Karşıyaka", "Bornova", "Buca", "Konak", "Bayraklı", "Çiğli", "Urla", "Çeşme"], note: "İzmir'de Karşıyaka, Bornova ve Bayraklı'nın modern dairelerinde soyut, pop art ve estetik poster temaları; Urla ve Çeşme'nin yazlık ve butik otellerinde ise açık tonlu, deniz ve gün batımı temalı panoramikler öne çıkar. Genç ve sanatla ilgili nüfusu sayesinde cesur, renkli tasarımlar da ilgi görür." },
  { plaka: 36, slug: "kars", name: "Kars", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Sarıkamış", "Kağızman", "Selim"], note: "Kars'ın Baltık mimarili taş binalarındaki kafe ve otellerde klasik eser ve şehir-mimari temaları, Sarıkamış'ın kayak otellerinde ise kar, orman ve at temalı büyük panoramikler mekâna uyum sağlar." },
  { plaka: 37, slug: "kastamonu", name: "Kastamonu", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Tosya", "Taşköprü", "İnebolu", "Cide"], note: "Kastamonu'nun ahşap konaklarında ve butik otellerinde klasik eser yorumları, orman ve doğa temalı tasarımlar; İnebolu ve Cide'nin sahil evlerinde ise deniz manzaralı panoramikler tercih edilir." },
  { plaka: 38, slug: "kayseri", name: "Kayseri", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Melikgazi", "Kocasinan", "Talas", "Develi", "İncesu"], note: "Kayseri'nin Talas ve Melikgazi'deki geniş dairelerinde lüks, altın detaylı soyut ve büyük ölçülü tasarımlar öne çıkar; mobilya üretiminin merkezlerinden biri olan şehirde showroom'lar teşhir için, sanayi firmaları da ofisleri için kurumsal cam tablo tercih eder." },
  { plaka: 39, slug: "kirklareli", name: "Kırklareli", bolge: "Marmara", kargo: "1–3", ilceler: ["Merkez", "Lüleburgaz", "Babaeski", "Vize", "Demirköy"], note: "Kırklareli'nde Lüleburgaz'ın yeni sitelerinde modern soyut ve 3'lü koltuk üstü tasarımlar, İğneada ve Demirköy'ün doğa otellerinde ise orman ve deniz temalı panoramikler öne çıkar; bağ evleri için şişe ve yaşam temalı tablolar da ilgi görür." },
  { plaka: 40, slug: "kirsehir", name: "Kırşehir", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Merkez", "Kaman", "Mucur", "Çiçekdağı"], note: "Kırşehir'in aile evlerinde klasik eser ve doğa temaları, termal tesislerinde panoramik manzaralar; Neşet Ertaş'ın şehrinde müzik temalı tasarımlar genç odalarında ve kafelerde ayrıca ilgi görür." },
  { plaka: 41, slug: "kocaeli", name: "Kocaeli", bolge: "Marmara", kargo: "1–3", ilceler: ["İzmit", "Gebze", "Başiskele", "Kartepe", "Darıca", "Gölcük", "Körfez"], note: "Kocaeli'de Gebze ve Dilovası'ndaki sanayi firmalarının ofislerinde kurumsal ve minimal cam tablolar, Başiskele ve Kartepe'nin yeni sitelerinde büyük ölçülü soyut ve doğa tasarımları öne çıkar; İstanbul'a yakınlığı sayesinde kargo süresi en kısa illerdendir." },
  { plaka: 42, slug: "konya", name: "Konya", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Beyşehir"], note: "Konya'nın Selçuklu ve Meram'daki geniş, yeni sitelerinde büyük salon duvarları için 90×140 cm tasarımlar ve 3'lü düzenler öne çıkar; sanayi ve tarım makineleri firmalarının ofislerinde kurumsal cam tablolar, aile evlerinde ise sade soyut ve doğa temaları tercih edilir." },
  { plaka: 43, slug: "kutahya", name: "Kütahya", bolge: "Ege", kargo: "2–3", ilceler: ["Merkez", "Tavşanlı", "Simav", "Gediz", "Emet"], note: "Kütahya'nın çini geleneğine sahip evlerinde ve kafelerinde klasik eser yorumları ve desenli tasarımlar, termal tesislerinde ise panoramik manzaralar öne çıkar; öğrenci evlerinde küçük ölçülü poster setleri sık tercih edilir." },
  { plaka: 44, slug: "malatya", name: "Malatya", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Battalgazi", "Yeşilyurt", "Doğanşehir", "Darende"], note: "Malatya'da deprem sonrası yenilenen konutlarda ferah, açık tonlu soyut ve doğa temalı tablolar tercih edilir; yeni taşınılan evlerde mutfak için 35×50, salon için 60×90 ölçü en çok istenen kombinasyondur." },
  { plaka: 45, slug: "manisa", name: "Manisa", bolge: "Ege", kargo: "2–3", ilceler: ["Yunusemre", "Şehzadeler", "Akhisar", "Turgutlu", "Salihli", "Soma"], note: "Manisa'nın organize sanayi bölgesindeki elektronik ve beyaz eşya firmalarının ofislerinde kurumsal ve minimal cam tablolar, Yunusemre ve Şehzadeler'in yeni dairelerinde ise modern soyut ve otomobil tasarımları öne çıkar." },
  { plaka: 46, slug: "kahramanmaras", name: "Kahramanmaraş", bolge: "Akdeniz", kargo: "2–4", ilceler: ["Onikişubat", "Dulkadiroğlu", "Elbistan", "Afşin", "Türkoğlu"], note: "Kahramanmaraş'ta yeniden yapılan konutlarda sade, ferah ve açık tonlu tasarımlar öne çıkar; tekstil ve dondurma üreticilerinin ofis ve mağazalarında marka görselli cam tablolar, aile salonlarında ise doğa ve klasik eser temaları tercih edilir." },
  { plaka: 47, slug: "mardin", name: "Mardin", bolge: "Güneydoğu Anadolu", kargo: "3–5", ilceler: ["Artuklu", "Kızıltepe", "Midyat", "Nusaybin"], note: "Mardin'in taş konak otellerinde, kafe ve restoranlarında klasik eser yorumları ve sıcak toprak tonlu tasarımlar tarihi dokuyla uyum sağlar; Artuklu ve Kızıltepe'nin yeni dairelerinde ise modern soyut ve 3'lü düzenler öne çıkar." },
  { plaka: 48, slug: "mugla", name: "Muğla", bolge: "Ege", kargo: "2–3", ilceler: ["Bodrum", "Fethiye", "Marmaris", "Menteşe", "Milas", "Datça"], note: "Muğla'da Bodrum, Fethiye ve Marmaris'in villa, butik otel ve beach club'larında deniz, gün batımı ve panoramik tasarımlar ile lüks, pop art temalı büyük ölçüler öne çıkar. Tuzlu ve nemli sahil havasında cam yüzeyin bozulmaması kanvasa göre belirgin bir avantajdır." },
  { plaka: 49, slug: "mus", name: "Muş", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Malazgirt", "Bulanık", "Varto"], note: "Muş'un aile evlerinde salonlar için sıcak tonlu soyut ve at temalı tasarımlar, Muş Ovası'nın geniş manzarasını çağrıştıran panoramikler tercih edilir; öğrenci evlerinde küçük ölçülü spor temaları öne çıkar." },
  { plaka: 50, slug: "nevsehir", name: "Nevşehir", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Merkez", "Ürgüp", "Avanos", "Derinkuyu", "Hacıbektaş"], note: "Nevşehir'in Kapadokya bölgesindeki mağara otelleri, butik pansiyonlar ve restoranlarda sıcak tonlu panoramikler, balon ve gökyüzü çağrıştıran fantastik tasarımlar mekânın atmosferini güçlendirir; taş duvarlarda çerçevesiz cam tablonun modern kontrastı ayrıca etkileyicidir." },
  { plaka: 51, slug: "nigde", name: "Niğde", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Merkez", "Bor", "Ulukışla", "Çiftlik"], note: "Niğde'nin aile evlerinde doğa, at ve klasik eser temaları, Aladağlar çevresindeki dağ evleri ve pansiyonlarda panoramik manzaralar öne çıkar; öğrenci evlerinde 35×50 ve 50×70 poster setleri tercih edilir." },
  { plaka: 52, slug: "ordu", name: "Ordu", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Altınordu", "Ünye", "Fatsa", "Perşembe"], note: "Ordu'nun Altınordu ve Ünye'deki sahil sitelerinde deniz manzaralı ve açık tonlu tasarımlar, Boztepe çevresindeki kafe ve restoranlarda panoramikler öne çıkar; nemli iklimde silinebilir cam yüzey pratik bir tercihtir." },
  { plaka: 53, slug: "rize", name: "Rize", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Çayeli", "Ardeşen", "Pazar", "Çamlıhemşin"], note: "Rize'nin Ayder ve Çamlıhemşin'deki yayla otelleri ve ahşap evlerinde orman, sis ve doğa temalı panoramikler, sahildeki modern dairelerde ise minimal soyut tasarımlar tercih edilir; yağışlı iklimde neme dayanıklı cam yüzey kanvasa göre çok daha uzun ömürlüdür." },
  { plaka: 54, slug: "sakarya", name: "Sakarya", bolge: "Marmara", kargo: "1–3", ilceler: ["Adapazarı", "Serdivan", "Erenler", "Akyazı", "Hendek", "Sapanca"], note: "Sakarya'da Serdivan'ın öğrenci ve genç nüfusuna yönelik evlerinde spor, sinema ve estetik poster temaları, Sapanca ve Kartepe yakınındaki bungalov ve villalarda ise göl ve orman temalı büyük panoramikler öne çıkar; otomotiv sanayisi nedeniyle otomobil koleksiyonu da ilgi görür." },
  { plaka: 55, slug: "samsun", name: "Samsun", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Atakum", "İlkadım", "Canik", "Bafra", "Çarşamba"], note: "Samsun'un Atakum'daki deniz manzaralı sitelerinde büyük ölçülü minimal ve deniz temalı tasarımlar, İlkadım ve Canik'in aile evlerinde 3'lü koltuk üstü düzenler, üniversite çevresinde ise genç temalı poster setleri öne çıkar." },
  { plaka: 56, slug: "siirt", name: "Siirt", bolge: "Güneydoğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Kurtalan", "Pervari", "Baykan"], note: "Siirt'in aile evlerinde sıcak tonlu soyut tablolar ve doğa temaları, misafir odalarında klasik eser yorumları tercih edilir; yeni konutlarda salon için 70×110 ölçü dengeli bir seçimdir." },
  { plaka: 57, slug: "sinop", name: "Sinop", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Boyabat", "Gerze", "Ayancık"], note: "Sinop'un yarımadadaki sahil evleri ve pansiyonlarında deniz, fener ve kuş temalı tasarımlar; merkezdeki kafe ve butik otellerde ise panoramik manzaralar mekânın sakin atmosferini tamamlar." },
  { plaka: 58, slug: "sivas", name: "Sivas", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Merkez", "Şarkışla", "Suşehri", "Zara", "Divriği"], note: "Sivas'ın yeni konut alanlarındaki geniş salonlarda soyut ve at-doğa temalı büyük ölçüler, üniversite öğrencilerinin evlerinde spor ve anime temaları, tarihi çarşı çevresindeki kafelerde ise klasik eser yorumları tercih edilir." },
  { plaka: 59, slug: "tekirdag", name: "Tekirdağ", bolge: "Marmara", kargo: "1–3", ilceler: ["Süleymanpaşa", "Çorlu", "Çerkezköy", "Kapaklı", "Ergene", "Şarköy"], note: "Tekirdağ'da Çorlu ve Çerkezköy'deki sanayi firmalarının ofislerinde kurumsal cam tablolar, Süleymanpaşa'nın sahil sitelerinde deniz temalı tasarımlar, Şarköy'ün bağ evleri ve şarap mekânlarında ise şişe ve yaşam temalı tablolar öne çıkar." },
  { plaka: 60, slug: "tokat", name: "Tokat", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Turhal", "Erbaa", "Niksar", "Zile"], note: "Tokat'ın aile evlerinde klasik eser ve natürmort tasarımlar, Niksar ve Erbaa'nın bahçeli evlerinde doğa ve kuş temaları öne çıkar; yeni sitelerde 3'lü koltuk üstü soyut düzenler tercih edilir." },
  { plaka: 61, slug: "trabzon", name: "Trabzon", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Ortahisar", "Akçaabat", "Yomra", "Araklı", "Of", "Sürmene"], note: "Trabzon'da futbol tutkusu nedeniyle spor temalı cam tablolar genç odalarında ve kafelerde çok ilgi görür; Ortahisar ve Akçaabat'ın deniz manzaralı dairelerinde minimal soyut, Uzungöl çevresindeki otellerde ise doğa ve göl temalı panoramikler öne çıkar." },
  { plaka: 62, slug: "tunceli", name: "Tunceli", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Pertek", "Ovacık", "Hozat"], note: "Tunceli'nin Munzur vadisine bakan evlerinde doğa, orman ve vahşi yaşam temalı tasarımlar, üniversite öğrencilerinin kira evlerinde ise müzik ve estetik poster temaları öne çıkar." },
  { plaka: 63, slug: "sanliurfa", name: "Şanlıurfa", bolge: "Güneydoğu Anadolu", kargo: "3–5", ilceler: ["Haliliye", "Eyyübiye", "Karaköprü", "Siverek", "Viranşehir"], note: "Şanlıurfa'nın Karaköprü ve Haliliye'deki geniş dairelerinde büyük ölçülü, altın detaylı ve lüks temalı tasarımlar tercih edilir; tarihi çarşı çevresindeki otel ve restoranlarda ise sıcak tonlu klasik eser yorumları mekânın dokusuyla uyum sağlar." },
  { plaka: 64, slug: "usak", name: "Uşak", bolge: "Ege", kargo: "2–3", ilceler: ["Merkez", "Banaz", "Eşme", "Sivaslı"], note: "Uşak'ın tekstil ve deri firmalarının ofislerinde kurumsal cam tablolar, aile evlerinde halı ve kilim renkleriyle uyumlu sıcak tonlu soyut tasarımlar öne çıkar." },
  { plaka: 65, slug: "van", name: "Van", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["İpekyolu", "Tuşba", "Edremit", "Erciş"], note: "Van'ın Tuşba ve Edremit'teki göl manzaralı evlerinde göl ve dağ temalı panoramikler, İpekyolu'nun kahvaltı salonları ve kafelerinde büyük ölçülü, silinebilir cam tablolar tercih edilir; kedi sevgisiyle bilinen şehirde sevimli hayvan temaları da ilgi görür." },
  { plaka: 66, slug: "yozgat", name: "Yozgat", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Merkez", "Sorgun", "Boğazlıyan", "Akdağmadeni", "Yerköy"], note: "Yozgat'ın aile evlerinde klasik eser ve doğa temaları, Çamlık Milli Parkı çevresindeki tesislerde orman temalı panoramikler, Sorgun'un termal otellerinde ise sakin tonlu soyut tasarımlar tercih edilir." },
  { plaka: 67, slug: "zonguldak", name: "Zonguldak", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Ereğli", "Çaycuma", "Devrek", "Alaplı"], note: "Zonguldak'ın deniz manzaralı yamaç evlerinde ve Ereğli'nin sahil sitelerinde deniz temalı ve minimal tasarımlar, sanayi ve enerji firmalarının ofislerinde ise kurumsal cam tablolar öne çıkar." },
  { plaka: 68, slug: "aksaray", name: "Aksaray", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Merkez", "Ortaköy", "Eskil", "Güzelyurt"], note: "Aksaray'ın otomotiv ve lojistik firmalarının ofislerinde otomobil ve kurumsal temalı cam tablolar, Ihlara Vadisi ve Güzelyurt'taki pansiyonlarda ise sıcak tonlu panoramik manzaralar öne çıkar." },
  { plaka: 69, slug: "bayburt", name: "Bayburt", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Demirözü", "Aydıntepe"], note: "Bayburt'un aile evlerinde doğa ve at temalı tasarımlar, üniversite öğrencilerinin kira evlerinde ise 35×50 ölçüde motivasyon yazılı ve spor temalı tablolar tercih edilir." },
  { plaka: 70, slug: "karaman", name: "Karaman", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Merkez", "Ermenek", "Ayrancı", "Kazımkarabekir"], note: "Karaman'da gıda ve bisküvi sanayisinin ofislerinde kurumsal cam tablolar, yeni sitelerdeki aile evlerinde ise mutfak için renkli küçük ölçüler ve salon için soyut 3'lü düzenler öne çıkar." },
  { plaka: 71, slug: "kirikkale", name: "Kırıkkale", bolge: "İç Anadolu", kargo: "2–3", ilceler: ["Merkez", "Yahşihan", "Keskin", "Delice"], note: "Kırıkkale'nin Ankara'ya yakın yeni konutlarında modern soyut ve otomobil temalı tasarımlar, sanayi çalışanlarının aile evlerinde ise doğa ve klasik eser temaları tercih edilir." },
  { plaka: 72, slug: "batman", name: "Batman", bolge: "Güneydoğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Kozluk", "Beşiri", "Sason"], note: "Batman'ın genç nüfusu nedeniyle evlerde spor, sinema ve anime temaları öne çıkar; yeni sitelerdeki geniş salonlarda ise altın detaylı soyut ve büyük ölçülü tasarımlar tercih edilir." },
  { plaka: 73, slug: "sirnak", name: "Şırnak", bolge: "Güneydoğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Cizre", "Silopi", "İdil"], note: "Şırnak'ta Cizre ve Silopi'nin ticaret ve lojistik firmalarının ofislerinde kurumsal cam tablolar, aile evlerinde ise sıcak tonlu soyut ve doğa temalı tasarımlar tercih edilir." },
  { plaka: 74, slug: "bartin", name: "Bartın", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Amasra", "Ulus", "Kurucaşile"], note: "Bartın'da Amasra'nın pansiyon, balık restoranı ve butik otellerinde deniz ve panoramik manzara tasarımları, merkezdeki ahşap evlerde ise doğa ve klasik eser temaları öne çıkar." },
  { plaka: 75, slug: "ardahan", name: "Ardahan", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Göle", "Posof", "Çıldır"], note: "Ardahan'ın uzun kışlı ikliminde evlerde sıcak tonlu soyut ve at-doğa temalı tasarımlar tercih edilir; Çıldır Gölü çevresindeki konaklama tesislerinde ise göl ve kar manzaralı panoramikler öne çıkar." },
  { plaka: 76, slug: "igdir", name: "Iğdır", bolge: "Doğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Aralık", "Tuzluca", "Karakoyunlu"], note: "Iğdır'ın aile evlerinde Ağrı Dağı'nı çağrıştıran dağ manzaralı panoramikler ve sıcak tonlu soyut tablolar, ticaret firmalarının ofislerinde ise kurumsal cam tablolar tercih edilir." },
  { plaka: 77, slug: "yalova", name: "Yalova", bolge: "Marmara", kargo: "1–3", ilceler: ["Merkez", "Çınarcık", "Çiftlikköy", "Termal", "Altınova"], note: "Yalova'nın Çınarcık ve Termal'deki yazlık, villa ve termal otellerinde deniz ve doğa temalı panoramikler öne çıkar; İstanbul'a yakınlığı sayesinde siparişler kısa sürede teslim edilir." },
  { plaka: 78, slug: "karabuk", name: "Karabük", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Safranbolu", "Eskipazar", "Yenice"], note: "Karabük'te Safranbolu'nun tarihi konak otelleri ve kafelerinde klasik eser yorumları mekânın ruhuyla uyuşur; üniversite öğrencilerinin yoğun olduğu merkezde ise genç temalı poster setleri ve spor tasarımları öne çıkar." },
  { plaka: 79, slug: "kilis", name: "Kilis", bolge: "Güneydoğu Anadolu", kargo: "3–5", ilceler: ["Merkez", "Musabeyli", "Elbeyli", "Polateli"], note: "Kilis'in aile evlerinde zeytin ve bağ bahçelerinin renklerini yansıtan doğa temalı tasarımlar ve sıcak tonlu soyut tablolar, işyerlerinde ise sade kurumsal cam tablolar tercih edilir." },
  { plaka: 80, slug: "osmaniye", name: "Osmaniye", bolge: "Akdeniz", kargo: "2–4", ilceler: ["Merkez", "Kadirli", "Düziçi", "Bahçe"], note: "Osmaniye'nin yeni konutlarında ferah, açık tonlu soyut ve doğa tasarımları, Karatepe-Aslantaş çevresindeki tesislerde ise orman ve göl temalı panoramikler öne çıkar." },
  { plaka: 81, slug: "duzce", name: "Düzce", bolge: "Karadeniz", kargo: "2–4", ilceler: ["Merkez", "Akçakoca", "Kaynaşlı", "Gölyaka", "Cumayeri"], note: "Düzce'de Akçakoca'nın sahil yazlıklarında deniz temalı tasarımlar, Kaynaşlı ve Gölyaka'nın bungalov ve doğa tesislerinde orman ve şelale temalı panoramikler, yeni sitelerde ise modern soyut düzenler tercih edilir." },
];

export const getIl = (slug: string) => iller.find((i) => i.slug === slug);
export const illerOf = (b: Bolge) => iller.filter((i) => i.bolge === b);

/** Bölgeye göre kargo açıklaması (il sayfalarındaki teslimat bölümü) */
export const bolgeKargoNote: Record<Bolge, string> = {
  Marmara: "Marmara illerine gönderiler İstanbul'dan çıktığı için Türkiye'deki en kısa teslim sürelerine sahiptir.",
  Ege: "Ege illerine gönderiler İstanbul'dan ana aktarma merkezleri üzerinden ulaşır; yaz aylarında tatil bölgelerinde bir gün ek süre olabilir.",
  Akdeniz: "Akdeniz illerine gönderiler aktarma merkezleri üzerinden ilerler; sahil ilçelerinde turizm sezonunda kargo yoğunluğu artabilir.",
  "İç Anadolu": "İç Anadolu illerine gönderiler Ankara ve Konya aktarma merkezleri üzerinden hızla dağıtılır.",
  Karadeniz: "Karadeniz illerine gönderiler sahil ve iç kesim güzergâhlarına göre farklı sürelerde ulaşır; yayla ve köy adreslerinde bir gün ek süre olabilir.",
  "Doğu Anadolu": "Doğu Anadolu illerine gönderiler uzun güzergâh nedeniyle birkaç gün daha sürebilir; kış aylarında hava koşulları süreyi etkileyebilir.",
  "Güneydoğu Anadolu": "Güneydoğu Anadolu illerine gönderiler Gaziantep ve Diyarbakır aktarma merkezleri üzerinden dağıtılır.",
};
